import globalClassNames from '../../style.d';
declare const classNames: typeof globalClassNames & {
  readonly workbenchContainer: 'workbenchContainer';
  readonly topToolBarBox: 'topToolBarBox';
  readonly topToolBarView: 'topToolBarView';
  readonly bodyContent: 'bodyContent';
  readonly leftBox: 'leftBox';
  readonly pluginIconBar: 'pluginIconBar';
  readonly pluginIconItem: 'pluginIconItem';
  readonly active: 'active';
  readonly pluginPanelBoxResizeBox: 'pluginPanelBoxResizeBox';
  readonly pluginHeader: 'pluginHeader';
  readonly pluginNameText: 'pluginNameText';
  readonly closeBtn: 'closeBtn';
  readonly fixedBtn: 'fixedBtn';
  readonly pluginPanelBox: 'pluginPanelBox';
  readonly rightResizeBox: 'rightResizeBox';
  readonly arrowCursor: 'arrowCursor';
  readonly rightBox: 'rightBox';
  readonly centerBox: 'centerBox';
  readonly subTopToolbarBox: 'subTopToolbarBox';
  readonly canvasBox: 'canvasBox';
  readonly scrollBox: 'scrollBox';
};
export = classNames;
